---
title: "set-index"
author: "Bruce C. Schardt"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{set-index}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setupSI, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```




```{r echo = TRUE, eval = FALSE}

dbCreateTable(conn = db,
              name = "daily_time_series",
              fields <- list(
                symbol = "VARCHAR(8)",
                date   = "DATE",
                sourceName = "VARCHAR(4)",
                sequenceID = "INTEGER",
                datetime = "DATETIME",
                epoch = "DOUBLE",
                open = "FLOAT",
                high = "FLOAT",
                low = "FLOAT",
                close = "FLOAT",
                volume = "DOUBLE",
                aOpen = "FLOAT",
                aHigh = "FLOAT",
                aLow = "FLOAT",
                aClose = "FLOAT",
                aVolume = "DOUBLE",
                dividendAmount = "FLOAT",
                splitCoefficient = "FLOAT"
              );

# add the composit primary key                            
dbAddPrimaryKey(conn = db, name = "daily_time_series", primary_key = c("symbol","date","sourceName")) 

# add seconary imdexes on date and sequenceID
dbAddIndex(conn = db, name = "daily_time_series", index = "sequenceID")
dbAddIndex(conn = db, name = "daily_time_series", index = "date")

```
